import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import localFont from 'next/font/local'
import NavBar from "@/components/navBar";
import { Roboto, Poppins, Oswald } from 'next/font/google'
import Footer from "@/components/footer";
import {I18nProviderClient} from "../../../locales/clients.js";
import {Toaster} from "sonner";



const roboto = Roboto({
    variable: "--font-roboto",
    weight: ['400', '700'],
    style: ['normal', 'italic'],
    subsets: ['latin'],
    display: 'swap',
})

const myFont = localFont({
    variable: "--font-myFont",
    src: "../../../public/fonts/EurostileExtendedBlack.ttf",
    display: "swap",
})


const poppins = Poppins({
    variable: "--font-poppins",
    subsets: ['latin'],
    weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

const oswald = Oswald({
    variable: "--font-oswald",
    subsets: ['latin'],
    weight: [ '200', '300', '400', '500', '600', '700'],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({children, params}) {
    const {locale} = await params
    return (
        <html lang="fr" className={`${poppins.variable}, ${myFont.variable}, ${oswald.variable}, ${roboto.variable}`}>
        <body >
        <Toaster  richColors closeButton/>
        <I18nProviderClient locale={locale}>
            <NavBar></NavBar>
            {children}
        </I18nProviderClient>
        <Footer />
        </body>
        </html>
    );
}
