import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import NavBar from "@/components/navBar";
import { Roboto } from 'next/font/google'
import Footer from "@/components/footer";
import {I18nProviderClient} from "../../../locales/clients.js";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


const roboto = Roboto({
    variable: "--font-roboto",
    weight: ['400', '700'],
    style: ['normal', 'italic'],
    subsets: ['latin'],
    display: 'swap',
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({children, params}) {
    const {locale} = await params
    return (
        <html lang="fr">
        <body className={`${roboto.variable} `}>
        <I18nProviderClient locale={locale}>
            <NavBar></NavBar>
            {children}
        </I18nProviderClient>
        <Footer />
        </body>
        </html>
    );
}
